### ISSUE TITLE
kong-response-size-limiting does not supported by the latested kong version

### ISSUE THREAD

**Issue by 2994265077** [Optum/kong-response-size-limiting#2]
According to the documentation, this plugin does not seem to support versions higher than 0.14.x. I am using the latest version of kong on docker. This plugin was not loaded nor activated.I used the command 'luarocks make *. Rockspec' to manually load this plugin. Kong informed me that the plugin was installed.Is there a way to use this plug-in in higher versions?Thanks.

**Comment by rsbrisci** [comment]
Hi @2994265077 

We currently run this plugin on Kong 1.3.0 (installed directly from `luarocks install kong-response-size-limtiing`), and haven't seen any issues.
Have you added it to your custom plugins list?

**Comment by jeremyjpj0916** [comment]
Closing due to stale issue.
